import { useState } from 'react';
import { Referral, Patient } from '../App';
import { FileText, Plus, X, Download, Mail } from 'lucide-react';
import { toast } from 'sonner';
import { PatientSearch } from './PatientSearch';
import { referralAPI } from '../api';

type ReferralGenerationProps = {
  referrals: Referral[];
  setReferrals: (referrals: Referral[]) => void;
  patients: Patient[];
};

export function ReferralGeneration({ referrals, setReferrals, patients }: ReferralGenerationProps) {
  const [showAddModal, setShowAddModal] = useState(false);
  const [viewingReferral, setViewingReferral] = useState<Referral | null>(null);
  const [selectedPatient, setSelectedPatient] = useState<Patient | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const specialties = [
    'Periodontics',
    'Endodontics',
    'Orthodontics',
    'Oral Surgery',
    'Prosthodontics',
    'Pediatric Dentistry',
    'Oral Pathology',
    'Oral Radiology',
    'X-Ray Imaging',
    'General Dentistry (Referral)'
  ];

  const handleCreateReferral = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsLoading(true);
    try {
      const formData = new FormData(e.currentTarget);
      
      if (!selectedPatient) {
        toast.error('Please select a patient');
        setIsLoading(false);
        return;
      }

      const newReferral = {
        patientId: selectedPatient.id,
        patientName: selectedPatient.name,
        referringDentist: formData.get('referringDentist') as string,
        referredTo: formData.get('referredTo') as string,
        specialty: formData.get('specialty') as string,
        reason: formData.get('reason') as string,
        date: formData.get('date') as string,
        urgency: formData.get('urgency') as 'routine' | 'urgent' | 'emergency',
      };

      const createdReferral = await referralAPI.create(newReferral);
      setReferrals([...referrals, createdReferral as Referral]);
      setShowAddModal(false);
      setSelectedPatient(null);
      
      // Show success notification
      toast.success(`Referral created for ${selectedPatient.name}`, {
        description: `Patient has been referred to ${newReferral.referredTo} for ${newReferral.specialty}. A notification has been sent to the patient.`,
        duration: 5000,
      });
    } catch (error) {
      console.error('Failed to create referral:', error);
      toast.error('Failed to create referral');
    } finally {
      setIsLoading(false);
    }
  };

  const deleteReferral = async (id: string | number) => {
    if (confirm('Are you sure you want to delete this referral?')) {
      try {
        await referralAPI.delete(id);
        setReferrals(referrals.filter(r => String(r.id) !== String(id)));
        toast.success('Referral deleted successfully');
      } catch (error) {
        console.error('Failed to delete referral:', error);
        toast.error('Failed to delete referral');
      }
    }
  };

  const downloadReferral = (referral: Referral) => {
    const patient = patients.find(p => String(p.id) === String(referral.patientId));
    
    const content = `
DENTAL REFERRAL

Date: ${new Date(referral.date).toLocaleDateString()}
Referral ID: ${referral.id}

PATIENT INFORMATION
Name: ${referral.patientName}
Date of Birth: ${patient?.dateOfBirth || 'N/A'}
Phone: ${patient?.phone || 'N/A'}
Email: ${patient?.email || 'N/A'}

REFERRING DENTIST
Dr. ${referral.referringDentist}

REFERRED TO
${referral.referredTo}
Specialty: ${referral.specialty}

URGENCY: ${referral.urgency.toUpperCase()}

REASON FOR REFERRAL
${referral.reason}

PATIENT MEDICAL HISTORY
${patient?.medicalHistory || 'None reported'}

ALLERGIES
${patient?.allergies || 'None reported'}

---
This referral was generated by the Dental Clinic Management System
Generated on: ${new Date().toLocaleString()}
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Referral_${referral.patientName.replace(/\s/g, '_')}_${referral.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const urgencyColors = {
    routine: 'bg-blue-100 text-blue-700 border-blue-500',
    urgent: 'bg-orange-100 text-orange-700 border-orange-500',
    emergency: 'bg-red-100 text-red-700 border-red-500',
  };

  return (
    <div className="p-8">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-3xl mb-2">Referral Generation</h1>
          <p className="text-gray-600">Create and manage patient referrals</p>
        </div>
        <button
          onClick={() => setShowAddModal(true)}
          className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 flex items-center gap-2"
        >
          <Plus className="w-5 h-5" />
          New Referral
        </button>
      </div>

      {/* Referrals List */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {referrals.map((referral) => (
          <div key={referral.id} className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
            <div className="flex justify-between items-start mb-4">
              <div>
                <h3 className="text-lg mb-1">{referral.patientName}</h3>
                <p className="text-sm text-gray-600">
                  {new Date(referral.date).toLocaleDateString()}
                </p>
              </div>
              <span className={`px-3 py-1 rounded text-xs border ${urgencyColors[referral.urgency]}`}>
                {referral.urgency}
              </span>
            </div>

            <div className="space-y-2 mb-4">
              <div>
                <p className="text-sm text-gray-600">Specialty</p>
                <p>{referral.specialty}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Referred To</p>
                <p>{referral.referredTo}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Reason</p>
                <p className="text-sm">{referral.reason}</p>
              </div>
            </div>

            <div className="flex gap-2 pt-4 border-t border-gray-200">
              <button
                onClick={() => setViewingReferral(referral)}
                className="flex-1 px-3 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 flex items-center justify-center gap-2 text-sm"
              >
                <FileText className="w-4 h-4" />
                View Full
              </button>
              <button
                onClick={() => downloadReferral(referral)}
                className="flex-1 px-3 py-2 bg-green-600 text-white rounded hover:bg-green-700 flex items-center justify-center gap-2 text-sm"
              >
                <Download className="w-4 h-4" />
                Download
              </button>
              <button
                onClick={() => deleteReferral(referral.id)}
                className="px-3 py-2 bg-red-600 text-white rounded hover:bg-red-700"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
          </div>
        ))}

        {referrals.length === 0 && (
          <div className="col-span-2 bg-white p-12 rounded-lg shadow-sm border border-gray-200 text-center">
            <FileText className="w-12 h-12 text-gray-400 mx-auto mb-4" />
            <p className="text-gray-600">No referrals created yet</p>
            <button
              onClick={() => setShowAddModal(true)}
              className="mt-4 px-6 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
            >
              Create Your First Referral
            </button>
          </div>
        )}
      </div>

      {/* Add Referral Modal */}
      {showAddModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg p-6 max-w-2xl w-full max-h-[90vh] overflow-y-auto">
            <div className="flex justify-between items-center mb-4">
              <h2 className="text-2xl">Create New Referral</h2>
              <button onClick={() => setShowAddModal(false)} className="text-gray-500 hover:text-gray-700">
                <X className="w-6 h-6" />
              </button>
            </div>
            <form onSubmit={handleCreateReferral} className="space-y-4">
              <div>
                <label className="block text-sm mb-1">Patient *</label>
                <PatientSearch
                  patients={patients}
                  selectedPatient={selectedPatient}
                  onSelectPatient={setSelectedPatient}
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm mb-1">Date *</label>
                  <input
                    type="date"
                    name="date"
                    required
                    defaultValue={new Date().toISOString().split('T')[0]}
                    className="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
                  />
                </div>
                <div>
                  <label className="block text-sm mb-1">Urgency *</label>
                  <select
                    name="urgency"
                    required
                    className="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
                  >
                    <option value="routine">Routine</option>
                    <option value="urgent">Urgent</option>
                    <option value="emergency">Emergency</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-sm mb-1">Referring Dentist *</label>
                <input
                  type="text"
                  name="referringDentist"
                  required
                  placeholder="Dr. Name"
                  className="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div>
                <label className="block text-sm mb-1">Specialty *</label>
                <select
                  name="specialty"
                  required
                  className="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  {specialties.map(specialty => (
                    <option key={specialty} value={specialty}>
                      {specialty}
                    </option>
                  ))}
                </select>
              </div>

              <div className="p-4 bg-blue-50 border border-blue-200 rounded">
                <p className="text-sm mb-2">
                  <strong>Common referral scenarios:</strong>
                </p>
                <ul className="text-sm text-blue-800 list-disc list-inside space-y-1">
                  <li>Select "X-Ray Imaging" when patient needs dental x-ray imaging</li>
                  <li>Select "General Dentistry (Referral)" when referring to another dentist (e.g., when unavailable)</li>
                  <li>Select "Orthodontics" for braces-related specialist referrals</li>
                </ul>
              </div>

              <div>
                <label className="block text-sm mb-1">Referred To (Specialist) *</label>
                <input
                  type="text"
                  name="referredTo"
                  required
                  placeholder="Dr. Name, Practice Name"
                  className="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div>
                <label className="block text-sm mb-1">Reason for Referral *</label>
                <textarea
                  name="reason"
                  required
                  rows={4}
                  placeholder="Detailed reason for referral, including relevant findings and recommended treatment..."
                  className="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div className="flex gap-3 justify-end">
                <button
                  type="button"
                  onClick={() => setShowAddModal(false)}
                  className="px-6 py-2 border border-gray-300 rounded hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-6 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
                >
                  Create Referral
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* View Referral Modal */}
      {viewingReferral && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg p-8 max-w-3xl w-full max-h-[90vh] overflow-y-auto">
            <div className="flex justify-between items-center mb-6 pb-4 border-b-2 border-gray-300">
              <h2 className="text-2xl">Dental Referral</h2>
              <button onClick={() => setViewingReferral(null)} className="text-gray-500 hover:text-gray-700">
                <X className="w-6 h-6" />
              </button>
            </div>

            <div className="space-y-6">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-sm text-gray-600 mb-1">Date</p>
                  <p>{new Date(viewingReferral.date).toLocaleDateString()}</p>
                </div>
                <div>
                  <p className="text-sm text-gray-600 mb-1">Referral ID</p>
                  <p>{viewingReferral.id}</p>
                </div>
              </div>

              <div className="pt-4 border-t border-gray-200">
                <h3 className="mb-3">Patient Information</h3>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p className="text-sm text-gray-600 mb-1">Name</p>
                    <p>{viewingReferral.patientName}</p>
                  </div>
                  {patients.find(p => String(p.id) === String(viewingReferral.patientId)) && (
                    <>
                      <div>
                        <p className="text-sm text-gray-600 mb-1">Date of Birth</p>
                        <p>{new Date(patients.find(p => String(p.id) === String(viewingReferral.patientId))!.dateOfBirth).toLocaleDateString()}</p>
                      </div>
                      <div>
                        <p className="text-sm text-gray-600 mb-1">Phone</p>
                        <p>{patients.find(p => String(p.id) === String(viewingReferral.patientId))!.phone}</p>
                      </div>
                      <div>
                        <p className="text-sm text-gray-600 mb-1">Email</p>
                        <p>{patients.find(p => String(p.id) === String(viewingReferral.patientId))!.email}</p>
                      </div>
                    </>
                  )}
                </div>
              </div>

              <div className="pt-4 border-t border-gray-200">
                <h3 className="mb-3">Referral Details</h3>
                <div className="space-y-3">
                  <div>
                    <p className="text-sm text-gray-600 mb-1">Referring Dentist</p>
                    <p>Dr. {viewingReferral.referringDentist}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 mb-1">Referred To</p>
                    <p>{viewingReferral.referredTo}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 mb-1">Specialty</p>
                    <p>{viewingReferral.specialty}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 mb-1">Urgency</p>
                    <span className={`inline-block px-3 py-1 rounded text-sm border ${urgencyColors[viewingReferral.urgency]}`}>
                      {viewingReferral.urgency.toUpperCase()}
                    </span>
                  </div>
                </div>
              </div>

              <div className="pt-4 border-t border-gray-200">
                <h3 className="mb-3">Reason for Referral</h3>
                <p className="text-gray-700 whitespace-pre-wrap">{viewingReferral.reason}</p>
              </div>

              {patients.find(p => String(p.id) === String(viewingReferral.patientId)) && (
                <div className="pt-4 border-t border-gray-200">
                  <h3 className="mb-3">Patient Medical Information</h3>
                  <div className="space-y-3">
                    <div>
                      <p className="text-sm text-gray-600 mb-1">Medical History</p>
                      <p>{patients.find(p => String(p.id) === String(viewingReferral.patientId))!.medicalHistory || 'None reported'}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-600 mb-1">Allergies</p>
                      <p className={patients.find(p => String(p.id) === String(viewingReferral.patientId))!.allergies !== 'None' ? 'text-red-600' : ''}>
                        {patients.find(p => String(p.id) === String(viewingReferral.patientId))!.allergies || 'None reported'}
                      </p>
                    </div>
                  </div>
                </div>
              )}

              <div className="flex gap-3 justify-end pt-6 border-t border-gray-200">
                <button
                  onClick={() => downloadReferral(viewingReferral)}
                  className="px-6 py-2 bg-green-600 text-white rounded hover:bg-green-700 flex items-center gap-2"
                >
                  <Download className="w-5 h-5" />
                  Download Referral
                </button>
                <button
                  onClick={() => setViewingReferral(null)}
                  className="px-6 py-2 border border-gray-300 rounded hover:bg-gray-50"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}